### ISSUE TITLE
isReactNativeBlob breaking nodejs without polyfill 

### ISSUE THREAD

**Issue by davellx** [therealparmesh/object-to-formdata#205]
Hello,

Until recently I could use serialize with my custom FromData instance within nodejs (from the "form-data" npm package) but with the introduction of `isReactNativeBlob` an error is thrown because it uses FormData directly.

Maybe it would be a solution to add an option to specify if we don't use React Native at all ? or pass the FormData constructor in options ?

**Comment by therealparmesh** [comment]
I'll take a look at this. Thanks!

**Comment by mifi** [comment]
I created a PR that resolves this

**Comment by therealparmesh** [comment]
Check out version 4.4.2!

@mifi Thank you so much for the PR! I decided to implement the fix a bit differently - rather than checking for the presence of a global FormData, I'm checking for the environment being React Native, since that's the cause of the special logic around Blobs in the first place.
