### ISSUE TITLE
Not supported the nested objects

### ISSUE THREAD

**Issue by IslamicProgrammer** [therealparmesh/object-to-formdata#220]
I have tried to convert the nested object to formData with serialize 

`let object = {
key1: "VALUE1",
key2: {
 nestedKey1: "NESTED_VALUE1"
}
}`

but it is not support this case ==(

**Comment by therealparmesh** [comment]
Can you provide a more thorough code example? The tests are passing for this case.

**Comment by lutaev-georgia** [comment]
I have the same issue.
The library doesn’t allow to send nested objects. For example, instead of `{ data: { user: 1 } }` it sends `{ data[user]: 1 }`. The same for files, backend (KoaJS) have to do dirty hacks like `files['documents[]']`
Also, it doesn’t allow to send boolean values. Instead of real true or false, it sends strings, e.g. 'true'.

**Comment by joemaffei** [comment]
> Also, it doesn’t allow to send boolean values. Instead of real true or false, it sends strings, e.g. 'true'.

That's because FormData values can only be strings or Blobs.
https://developer.mozilla.org/en-US/docs/Web/API/FormData/append

**Comment by IslamicProgrammer** [comment]
Thank you a lot
